expenses/urls.py
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import path, reverse_lazy
from .models import Expense, Category
from .views import ExpenseListView, CategoryListView


urlpatterns = [
    path('expense/list/',
         ExpenseListView.as_view(),
         name='expense-list'),
    path('expense/create/',
         CreateView.as_view(
            model=Expense,
            fields='__all__',
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_update.html'
         ),
         name='expense-create'),
    path('expense/<int:pk>/edit/',
         UpdateView.as_view(
            model=Expense,
            fields='__all__',
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_update.html'
         ),
         name='expense-edit'),
    path('expense/<int:pk>/delete/',
         DeleteView.as_view(
            model=Expense,
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_delete.html'
         ),
         name='expense-delete'),

    path('category/list/',
         CategoryListView.as_view(),
         name='category-list'),
    path('category/create/',
         CreateView.as_view(
            model=Category,
            fields='__all__',
            success_url=reverse_lazy('expenses:category-list'),
            template_name='generic_update.html'
         ),
         name='category-create'),
    path('category/<int:pk>/delete/',
         DeleteView.as_view(
            model=Category,
            success_url=reverse_lazy('expenses:category-list'),
            template_name='generic_delete.html'
         ),
         name='category-delete'),
]

project/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('',
         RedirectView.as_view(pattern_name='expenses:expense-list'),
         name='dashboard'),
    path('expenses/',
         include(('expenses.urls', 'expenses'), namespace='expenses')),
]

expenses/models.py
import datetime
from django.db import models


class Category(models.Model):
    class Meta:
        ordering = ('name',)

    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.name}'

    @property
    def total_category_amount(self):
        category_amounts_list = Expense.objects.filter(category__name=self.name)
        category_amount_sum = 0
        for amount in [item.amount for item in category_amounts_list]:
            category_amount_sum += amount
        return float(category_amount_sum)


class Expense(models.Model):
    class Meta:
        ordering = ('-date', '-pk')

    category = models.ForeignKey(Category, models.PROTECT, null=True, blank=True)
    name = models.CharField(max_length=50)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    date = models.DateField(default=datetime.date.today, db_index=True)

    def __str__(self):
        return f'{self.date} {self.name} {self.amount}'

    # @property
    # def total_amount_spent(self):
    #     return int(sum(list(Expense.objects.values_list('amount', flat=True))))

    @property
    def replaced_date(self):
        return self.date.replace(day=1)

expenses/forms.py
from collections import OrderedDict
from django import forms
from .models import Expense, Category


class ExpenseSearchForm(forms.Form):
    date_from = forms.DateField(required=False)
    date_to = forms.DateField(required=False)

    category = forms.ModelMultipleChoiceField(
        required=False,
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        fields = ('category', 'date',)


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].required = False

expenses/views.py
import datetime
from django.views.generic.list import ListView

from .forms import ExpenseSearchForm
from .models import Expense, Category
from .reports import (summary_per_category, summary_per_months,
    total_amount_spent)


class ExpenseListView(ListView):
    model = Expense
    paginate_by = 10

    def get_ordering(self):
        ordering = self.request.GET.get('order_by')
        return ordering

    def get_context_data(self, *, object_list=None, **kwargs):

        queryset = object_list if object_list is not None else self.object_list

        if self.request.GET:
            form = ExpenseSearchForm(self.request.GET)

            if form.is_valid():
                categories = form.cleaned_data.get('category', '')
                date_from = form.data.get('date_from', '')
                date_to = form.data.get('date_to', '')

                if categories:
                    queryset = queryset.filter(category__in=categories)
                if date_from and date_to:
                    queryset = queryset.filter(
                        date__gte=date_from, date__lte=date_to
                    )
                elif date_from:
                    date_to = datetime.date.today()
                    queryset = queryset.filter(
                        date__gte=date_from, date__lte=date_to
                    )
                elif date_to:
                    date_from = datetime.date(1900, 1, 1)
                    queryset = queryset.filter(
                        date__gte=date_from, date__lte=date_to
                    )

                ordering = self.get_ordering()
                if ordering:
                    queryset = queryset.order_by(ordering)
        else:
            form = ExpenseSearchForm()

        return super().get_context_data(
            form=form,
            object_list=queryset,
            total_amount_spent=total_amount_spent(queryset),
            summary_per_category=summary_per_category(queryset),
            summary_per_months=summary_per_months(queryset),
            **kwargs)


class CategoryListView(ListView):
    model = Category
    paginate_by = 5

expenses/templates/expenses/category_list.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'expenses:category-create' %}">add</a>

<table border="1">
	<thead>
		<tr>
			<th>name</th>
            <th>total amount</th>
			<th>actions</th>
		</tr>
	</thead>
	<tbody>
		{% for obj in object_list %}
		<tr>
			<td>
				{{ obj.name }}
			</td>
            <td>
				{{ obj.total_category_amount|floatformat:2 }}
			</td>
			<td>
				<a href="{% url 'expenses:category-delete' obj.id %}">delete</a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

expenses/templates/expenses/expense_list.html
{% extends "base.html" %}

{% block content %}
{% load custom_tags %}

<a href="{% url 'expenses:expense-create' %}">add</a>

<form method="get" action="">
  {{form.as_p}}
  <button type="submit">search</button>
</form>
<br>
<table border="1">
	<caption>Expenses</caption>
	<thead>
	  <tr>
		<th>no.</th>
		<th><a href="?{% url_replace request 'order_by' 'category' '-' %}">category</a></th>
		<th>name</th>
		<th>amount</th>
		<th><a href="?{% url_replace request 'order_by' 'date' '-' %}">date</a></th>
		<th>actions</th>
	  </tr>
	</thead>
	<tbody>
	{% for obj in object_list %}
	  <tr>
		<td>{{ page_obj.start_index|add:forloop.counter0 }}.</td>
		<td>{{ obj.category|default:"-" }}</td>
		<td>{{ obj.name|default:"-" }}</td>
		<td>{{ obj.amount|floatformat:2 }}</td>
		<td>{{ obj.date }}</td>
		<td>
		  <a href="{% url 'expenses:expense-edit' obj.id %}">edit</a>
		  <a href="{% url 'expenses:expense-delete' obj.id %}">delete</a>
		</td>
	  </tr>
	  {% empty %}
	  <tr>
		<td colspan="5">no items</td>
	  </tr>
	{% endfor %}
	</tbody>
</table>
{% include "_pagination.html" %}
<hr>
<table border="1" style="width:35%">
	<caption>Total amount spent for expenses</caption>
	<thead>
	  <tr>
		<th>amount</th>
	  </tr>
	</thead>
	<tbody>
	  <tr>
		<td style="text-align: center">{{ total_amount_spent|floatformat:2 }}</td>
	  </tr>
	</tbody>
</table>

<hr>
<table border="1">
  <caption>Summary per category</caption>
  <tr>
    {% for category, total in summary_per_category.items %}
	<tr>
		<td>{{category}}:</td>
		<td>{{total|floatformat:2}}</td>
	</tr>
	{% endfor %}
  </tr>
</table>

<hr>
<table border="1">
  <caption>Summary per months</caption>
  <tr>
    {% for date, total in summary_per_months.items %}
	<tr>
		<td>{{date|date:"F"}} {{date.year}}:</td>
		<td>{{total|floatformat:2}}</td>
	</tr>
	{% endfor %}
  </tr>
</table>
{% endblock %}

project/templates/_pagination.html
<div class="pagination">
    <span class="pagination__nav">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

project/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block meta_title %}Expenses app{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  </head>
  <body>
	<a href="{% url 'expenses:expense-list' %}">Expenses</a> |
	<a href="{% url 'expenses:category-list' %}">Categories</a> |
	<hr>
    {% block content %}{% endblock %}
  </body>
</html>

project/templates/generic_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Confirm removing "{{object}}"</h1>
<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">delete</button>
</form>

{% endblock %}

project/templates/generic_update.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">save</button>
</form>

{% endblock %}